use bd_cenagas;
update roles set registro_eliminado = 0;
update usuarios set registro_eliminado = 0;
update anexos set registro_eliminado = 0;
update residencias set registro_eliminado = 0;
update gasoductos set registro_eliminado = 0;
update tramos set registro_eliminado = 0;
update instalaciones set registro_eliminado = 0;
update adc_actividades set registro_eliminado = 0;
update adc_normativas set registro_eliminado = 0;