// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCenagas.Data;

namespace SistemaCenagas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220719151733_Tablas")]
    partial class Tablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("SistemaCenagas.Models.ADC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Actualizacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Folio")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_LiderEquipoVerificador")
                        .HasColumnType("int");

                    b.Property<int>("Id_ProponenteCambio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_ResponsableADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_Suplente")
                        .HasColumnType("int");

                    b.Property<string>("PreArranque")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Actividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ADC_Actividades");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<string>("EstatusADC")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo2")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Residencia")
                        .HasColumnType("int");

                    b.Property<string>("PresentoARP")
                        .HasColumnType("longtext");

                    b.Property<string>("Prestacion_Servicio")
                        .HasColumnType("longtext");

                    b.Property<string>("Proceso")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Resultados_Analisis")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultados_Propuesta")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Cambio")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Gasoducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Tramo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo1");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo2");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accesorio_o_Ducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Componente_o_Dispositivo")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion_Cambio")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion_Riesgo")
                        .HasColumnType("longtext");

                    b.Property<string>("Equipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Estacion_Compresion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estacion_Medicion_y_Regulacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Inicio")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Registro")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Termino")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo1")
                        .HasColumnType("int");

                    b.Property<int>("Id_Anexo2")
                        .HasColumnType("int");

                    b.Property<int>("Id_Director_Ejecutivo_Mantenimiento_y_Seguridad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Director_Ejecutivo_Operacion")
                        .HasColumnType("int");

                    b.Property<int>("Id_Director_Seguridad_Industrial")
                        .HasColumnType("int");

                    b.Property<int>("Id_Responsable_ADC")
                        .HasColumnType("int");

                    b.Property<string>("Instrumento")
                        .HasColumnType("longtext");

                    b.Property<double>("Inversion_Cambio")
                        .HasColumnType("double");

                    b.Property<string>("Justificacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero_Identificacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Otra_Documentacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Otro_Elemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_ADC")
                        .HasColumnType("longtext");

                    b.Property<string>("Trampa_Envios_y_Recibo_Diablos")
                        .HasColumnType("longtext");

                    b.Property<string>("Valvula")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo3");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo3_CatalogoTipoDocumentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumentacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo3_CatalogoTipoDocumentacion");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo3_Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Anotaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Check")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo3")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Responsable_Area")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo3_Documentacion");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo3_DocumentacionResponsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Check")
                        .HasColumnType("longtext");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo3")
                        .HasColumnType("int");

                    b.Property<int>("Id_Documentacion")
                        .HasColumnType("int");

                    b.Property<int>("Id_Responsable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo3_DocumentacionResponsable");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autorizacion_Inicio_Operacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Retiro_Cambio_Temporal")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo1")
                        .HasColumnType("int");

                    b.Property<int>("Id_Anexo3")
                        .HasColumnType("int");

                    b.Property<int>("Id_Residente")
                        .HasColumnType("int");

                    b.Property<string>("Propuesta_Inicio_Operacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Tiempo_Estimado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo4");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Anio_Cambio")
                        .HasColumnType("longtext");

                    b.Property<string>("Anio_Retiro")
                        .HasColumnType("longtext");

                    b.Property<string>("Confirmacion_Retiro_Cambios_Temporales")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Dia_Cambio")
                        .HasColumnType("longtext");

                    b.Property<string>("Dia_Retiro")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo1")
                        .HasColumnType("int");

                    b.Property<int>("Id_Anexo3")
                        .HasColumnType("int");

                    b.Property<int>("Id_Responsable_Cambio_Temporal")
                        .HasColumnType("int");

                    b.Property<string>("Mes_Cambio")
                        .HasColumnType("longtext");

                    b.Property<string>("Mes_Retiro")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo5");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo6", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Inicio")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Recepcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Termino")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo1")
                        .HasColumnType("int");

                    b.Property<int>("Id_anexo3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo6");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexo6_Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Check")
                        .HasColumnType("longtext");

                    b.Property<string>("Elemento")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo6")
                        .HasColumnType("int");

                    b.Property<string>("Seccion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexo6_Documentacion");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Anexos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Anexos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Archivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_ADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proceso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<float>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Archivos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Equipo_Verificador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_ADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_LiderEquipoVerificador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ADC_Equipo_Verificador");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Equipo_Verificador_Integrantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Equipo_Verificador_ADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ADC_Equipo_Verificador_Integrantes");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Normativas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Actividad")
                        .HasColumnType("int");

                    b.Property<string>("Registro")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Normativas");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Procesos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Activo")
                        .HasColumnType("longtext");

                    b.Property<float>("Avance")
                        .HasColumnType("float");

                    b.Property<string>("Confirmado")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Faltante_Comentarios")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_ADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_Actividad")
                        .HasColumnType("int");

                    b.Property<string>("Plan_Accion")
                        .HasColumnType("longtext");

                    b.Property<string>("Terminado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADC_Procesos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.DDV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DDV");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<int>("Id_DireccionEjecutiva")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Direccion_Ejecutiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Unidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Direccion_Ejecutiva");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ElementoS3S", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Elemento")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ElementoS3S");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Especialidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Capital")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Etapa_Realizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Avance")
                        .HasColumnType("int");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Etapa")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etapa_Realizada");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Fuente_Deteccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Fuente")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fuente_Deteccion");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Gasoductos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Denominacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion_Pemex")
                        .HasColumnType("longtext");

                    b.Property<float>("Diametro_o_pulgadas")
                        .HasColumnType("float");

                    b.Property<string>("Gasoducto")
                        .HasColumnType("longtext");

                    b.Property<float>("Longitud_Metros")
                        .HasColumnType("float");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Sistema")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Ducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Gasoducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Pemex")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gasoductos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Instalaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Altitud_Z_decimal")
                        .HasColumnType("float");

                    b.Property<string>("Clase")
                        .HasColumnType("longtext");

                    b.Property<string>("Gmas_Pemex")
                        .HasColumnType("longtext");

                    b.Property<string>("Instalacion")
                        .HasColumnType("longtext");

                    b.Property<float>("Km")
                        .HasColumnType("float");

                    b.Property<float>("Latitud_Y_decimal")
                        .HasColumnType("float");

                    b.Property<float>("Longitud_X_decimal")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Residencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector_Pemex")
                        .HasColumnType("longtext");

                    b.Property<string>("Sistema")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Instalacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Tramo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Instalaciones");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Con_ADC")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Actualizacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Folio")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_ADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_LiderEquipoVerificador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Responsable")
                        .HasColumnType("int");

                    b.Property<int>("Id_Suplente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreArranque");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Actividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Actividades");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Elaboracion")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Prearranque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo1");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo1_Actividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accion_Descriptiva")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo1")
                        .HasColumnType("int");

                    b.Property<int>("Id_Responsable")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo1_Actividades");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo1_Actividades_Acciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<float>("Avance")
                        .HasColumnType("float");

                    b.Property<string>("Concluida")
                        .HasColumnType("longtext");

                    b.Property<string>("Evidencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Inicio")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha_Termino")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo1_Actividades")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo1_Actividades_Acciones");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo1_Actividades_Acciones_ArchivosEvidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Accion")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<float>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo1_Actividades_Acciones_ArchivosEvidencia");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Elaboracion")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Prearranque")
                        .HasColumnType("int");

                    b.Property<int>("Id_Residencia")
                        .HasColumnType("int");

                    b.Property<int>("Numero_Revisiones")
                        .HasColumnType("int");

                    b.Property<int>("Revision_Actual")
                        .HasColumnType("int");

                    b.Property<string>("Ut_Gasoducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Tramo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo2");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo2_Seccion2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_Anexo2")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo2_Seccion2");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo2_Seccion2_Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tarea")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo2_Seccion2_Catalogo");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo2_Seccion2_ElementosRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Atendido")
                        .HasColumnType("longtext");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Elemento_Revision")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo2_Seccion2")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Hallazgo")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Revision")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo2_Seccion2_ElementosRevision");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo2_Seccion2_ElementosRevision_Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_Tarea")
                        .HasColumnType("int");

                    b.Property<string>("Subtarea")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo2_Seccion2_ElementosRevision_Catalogo");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Anexo2_Seccion3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion_Hallazgo")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion_Recomendacion")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Anexo2")
                        .HasColumnType("int");

                    b.Property<int>("Id_Responsable")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext");

                    b.Property<string>("Riesgo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Anexo2_Seccion3");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Archivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_PreArranque")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proceso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<float>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Archivos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Equipo_Verificador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_LiderEquipoVerificador")
                        .HasColumnType("int");

                    b.Property<int>("Id_PreArranque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Equipo_Verificador");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Equipo_Verificador_Integrantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Equipo_Verificador_PreArranque")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Equipo_Verificador_Integrantes");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Normativas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Actividad")
                        .HasColumnType("int");

                    b.Property<string>("Registro")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Normativas");
                });

            modelBuilder.Entity("SistemaCenagas.Models.PreArranque_Procesos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Activo")
                        .HasColumnType("longtext");

                    b.Property<float>("Avance")
                        .HasColumnType("float");

                    b.Property<string>("Confirmado")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Faltante_Comentarios")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Actividad")
                        .HasColumnType("int");

                    b.Property<int>("Id_PreArranque")
                        .HasColumnType("int");

                    b.Property<string>("Plan_Accion")
                        .HasColumnType("longtext");

                    b.Property<string>("Terminado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PreArranque_Procesos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Proyecto_Miembros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proyecto_Miembros");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Proyectos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_ADC")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado_PreArranque")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Puestos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Privilegios")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Residencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Postal")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Residencias");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Privilegios")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Denominacion")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sistema");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Instalacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Tramos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Diametro")
                        .HasColumnType("float");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<float>("Espesor_Nominal")
                        .HasColumnType("float");

                    b.Property<string>("Fecha_Construccion")
                        .HasColumnType("longtext");

                    b.Property<float>("Km_Fin")
                        .HasColumnType("float");

                    b.Property<float>("Km_Inicio")
                        .HasColumnType("float");

                    b.Property<float>("Longitud_Metros")
                        .HasColumnType("float");

                    b.Property<string>("Residencia")
                        .HasColumnType("longtext");

                    b.Property<float>("SMYS")
                        .HasColumnType("float");

                    b.Property<string>("Tramo")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Gasoducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Tramo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tramos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Unidad");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Confirmar_Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Puesto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Image_Url")
                        .HasColumnType("longtext");

                    b.Property<string>("Materno")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Notificacion_ADC")
                        .HasColumnType("longtext");

                    b.Property<string>("Notificacion_Proyecto")
                        .HasColumnType("longtext");

                    b.Property<string>("Notificacion_Tarea")
                        .HasColumnType("longtext");

                    b.Property<string>("Nueva_Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Paterno")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Zonas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });
#pragma warning restore 612, 618
        }
    }
}
