// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCenagas.Data;

namespace SistemaCenagas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220324223300_Proyecto_Miembros")]
    partial class Proyecto_Miembros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("SistemaCenagas.Models.ADC", b =>
                {
                    b.Property<int>("Id_ADC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fecha_Actualizacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Folio")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Lider")
                        .HasColumnType("int");

                    b.Property<int>("Id_ProponenteCambio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_ResponsableADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_Suplente")
                        .HasColumnType("int");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_ADC");

                    b.ToTable("ADC");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Actividades", b =>
                {
                    b.Property<int>("Id_Actividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Actividad")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_Actividad");

                    b.ToTable("ADC_Actividades");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Normativas", b =>
                {
                    b.Property<int>("Id_Normativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Actividad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Anexo")
                        .HasColumnType("int");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Normativa");

                    b.ToTable("ADC_Normativas");
                });

            modelBuilder.Entity("SistemaCenagas.Models.ADC_Procesos", b =>
                {
                    b.Property<int>("Id_Proceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Avance")
                        .HasColumnType("float");

                    b.Property<string>("Faltante_Comentarios")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_ADC")
                        .HasColumnType("int");

                    b.Property<int>("Id_Actividad")
                        .HasColumnType("int");

                    b.Property<string>("Plan_Accion")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_Proceso");

                    b.ToTable("ADC_Procesos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Anexo1", b =>
                {
                    b.Property<int>("Id_PropuestaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Residencia")
                        .HasColumnType("int");

                    b.Property<string>("Prestacion_Servicio")
                        .HasColumnType("longtext");

                    b.Property<string>("Proceso")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Resultados_Analisis")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultados_Propuesta")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Cambio")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Gasoducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Ut_Tramo")
                        .HasColumnType("longtext");

                    b.HasKey("Id_PropuestaCambio");

                    b.ToTable("Anexo1");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Anexos", b =>
                {
                    b.Property<int>("Id_Anexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_Anexo");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Gasoductos", b =>
                {
                    b.Property<int>("Id_Instalacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Denominacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Descripcion_Pemex")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Diametro_o_pulgadas")
                        .HasColumnType("float");

                    b.Property<string>("Gasoducto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Longitud_Metros")
                        .HasColumnType("float");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Sistema")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Ducto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Gasoducto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Pemex")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id_Instalacion");

                    b.ToTable("Gasoductos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Instalaciones", b =>
                {
                    b.Property<int>("Id_Instalacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Altitud_Z_decimal")
                        .HasColumnType("float");

                    b.Property<string>("Clase")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Gmas_Pemex")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Instalacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Km")
                        .HasMaxLength(200)
                        .HasColumnType("float");

                    b.Property<float>("Latitud_Y_decimal")
                        .HasColumnType("float");

                    b.Property<float>("Longitud_X_decimal")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Residencia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sector_Pemex")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sistema")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Instalacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Tramo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id_Instalacion");

                    b.ToTable("Instalaciones");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Proyecto_Miembros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Proyecto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proyecto_Miembros");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Proyectos", b =>
                {
                    b.Property<int>("Id_Proyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado_ADC")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_Proyecto");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Residencias", b =>
                {
                    b.Property<int>("Id_Residencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_Residencia");

                    b.ToTable("Residencias");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Roles", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Privilegios")
                        .HasColumnType("longtext");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Tramos", b =>
                {
                    b.Property<int>("Id_Tramo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Diametro")
                        .HasColumnType("float");

                    b.Property<float>("Espesor_Nominal")
                        .HasColumnType("float");

                    b.Property<string>("Fecha_Construccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Km_Fin")
                        .HasColumnType("float");

                    b.Property<float>("Km_Inicio")
                        .HasColumnType("float");

                    b.Property<float>("Longitud_Metros")
                        .HasColumnType("float");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Residencia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("SMYS")
                        .HasColumnType("float");

                    b.Property<string>("Tramo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Gasoducto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ut_Tramo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id_Tramo");

                    b.ToTable("Tramos");
                });

            modelBuilder.Entity("SistemaCenagas.Models.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Confirmar_Password")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estatus")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Image_Url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Materno")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Nueva_Password")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Paterno")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Registro_Eliminado")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
